name: haskell-auth
version: 0.1.0.0
github: "zdrazil/haskell-auth"
license: BSD3
author: "Vladimir Zdrazil"
maintainer: "git@vzdrazil.com"
copyright: "2018 Vladimir Zdrazil"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/zdrazil/haskell-auth#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - classy-prelude
  - data-has
  - mtl
  - pcre-heavy
  - string-random
  - time

library:
  source-dirs: src

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - ConstraintKinds
  - FlexibleContexts

executables:
  haskell-auth-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-auth

tests:
  haskell-auth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-auth
